# Copy keys from here into Streamlit Cloud (App -> Settings -> Secrets)
# Never commit real secrets to version control.

# Optional API base URL if you host the Node API elsewhere
API_URL = "https://your-api.example.com"
